version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend-container

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"   # 👈 frontend visible on localhost:3000
    container_name: frontend-container
    depends_on:
      - backend
